# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/node-9.6.22" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "9.6.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-9.6.22.tgz";
        sha512 = "029z88xrbdj4nj9krawd3a22gcdvjl86szxxpg9cah3f0kwvfr772lyp1ml50r3s91052i2jizvgbc0cysb0f233w6wjm3k9h93v224";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "applescript-1.0.0" = {
      name = "applescript";
      packageName = "applescript";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/applescript/-/applescript-1.0.0.tgz";
        sha1 = "bb87af568cad034a4e48c4bdaf6067a3a2701317";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "auto-launch-5.0.5" = {
      name = "auto-launch";
      packageName = "auto-launch";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/auto-launch/-/auto-launch-5.0.5.tgz";
        sha512 = "1s8ypnynvl0yp6y6k8w7bivny77d894bq2sjxww2ndxvbgfk809h722jlsxzyg9xn6cpgwyw1857kpx8wgp70mvc368r1d1d3i4b5x6";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.7.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.7.0.tgz";
        sha512 = "3rkdcpm3myysvq9nj6plgvpngzsbv7qk1wvb9f4m3gcsl23pf5x0hyph02svyl2v1lgjji8kl75ii7q04lhhhgjyw1irbinmxsl6qyz";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "bignumber.js-2.4.0" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-2.4.0.tgz";
        sha1 = "838a992da9f9d737e0f4b2db0be62bb09dd0c5e8";
      };
    };
    "bmp-js-0.0.3" = {
      name = "bmp-js";
      packageName = "bmp-js";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bmp-js/-/bmp-js-0.0.3.tgz";
        sha1 = "64113e9c7cf1202b376ed607bf30626ebe57b18a";
      };
    };
    "buffer-equal-0.0.1" = {
      name = "buffer-equal";
      packageName = "buffer-equal";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal/-/buffer-equal-0.0.1.tgz";
        sha1 = "91bc74b11ea405bc916bc6aa908faafa5b4aac4b";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "combined-stream-1.0.6" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz";
        sha1 = "723e7df6e801ac5613113a7e445a9b69cb632818";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "deep-equal-1.0.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz";
        sha1 = "f5d260292b660e084eff4cdbc9f08ad3247448b5";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "dom-walk-0.1.1" = {
      name = "dom-walk";
      packageName = "dom-walk";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-walk/-/dom-walk-0.1.1.tgz";
        sha1 = "672226dc74c8f799ad35307df936aba11acd6018";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "electron-window-state-4.1.1" = {
      name = "electron-window-state";
      packageName = "electron-window-state";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-window-state/-/electron-window-state-4.1.1.tgz";
        sha1 = "6b34fdc31b38514dfec8b7c8f7b5d4addb67632d";
      };
    };
    "es6-promise-3.3.1" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-3.3.1.tgz";
        sha1 = "a08cdde84ccdbf34d027a1451bc91d4bcd28a613";
      };
    };
    "exif-parser-0.1.12" = {
      name = "exif-parser";
      packageName = "exif-parser";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/exif-parser/-/exif-parser-0.1.12.tgz";
        sha1 = "58a9d2d72c02c1f6f02a0ef4a9166272b7760922";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha1 = "c053477817c86b51daa853c81e059b733d023614";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "file-type-3.9.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "3.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-3.9.0.tgz";
        sha1 = "257a078384d1db8087bc449d107d52a52672b9e9";
      };
    };
    "for-each-0.3.3" = {
      name = "for-each";
      packageName = "for-each";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-each/-/for-each-0.3.3.tgz";
        sha512 = "2dikmdxwassw4w48vv82swjv4v1zx2sivsgcnxi3zi0imzw165ba8vaxgawz0wz4fgf138hvvc3xc5znr2wmz07r74dp8z6kqp1z9lf";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.2" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.2.tgz";
        sha1 = "4970498be604c20c005d4f5c23aecd21d6b49099";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "global-4.3.2" = {
      name = "global";
      packageName = "global";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/global/-/global-4.3.2.tgz";
        sha1 = "e76989268a6c74c38908b1305b10fc0e394e9d0f";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.0.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz";
        sha1 = "ba402c266194f15956ef15e0fcf242993f6a7dfd";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "ip-regex-1.0.3" = {
      name = "ip-regex";
      packageName = "ip-regex";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-regex/-/ip-regex-1.0.3.tgz";
        sha1 = "dc589076f659f419c222039a33316f1c7387effd";
      };
    };
    "is-callable-1.1.3" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.3.tgz";
        sha1 = "86eb75392805ddc33af71c92a0eedf74ee7604b2";
      };
    };
    "is-function-1.0.1" = {
      name = "is-function";
      packageName = "is-function";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-function/-/is-function-1.0.1.tgz";
        sha1 = "12cfb98b65b57dd3d193a3121f5f6e2f437602b5";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jimp-0.2.28" = {
      name = "jimp";
      packageName = "jimp";
      version = "0.2.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/jimp/-/jimp-0.2.28.tgz";
        sha1 = "dd529a937190f42957a7937d1acc3a7762996ea2";
      };
    };
    "jpeg-js-0.2.0" = {
      name = "jpeg-js";
      packageName = "jpeg-js";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jpeg-js/-/jpeg-js-0.2.0.tgz";
        sha1 = "53e448ec9d263e683266467e9442d2c5a2ef5482";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsonfile-2.4.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-2.4.0.tgz";
        sha1 = "3736a2b428b87bbda0cc83b53fa3d633a35c2ae8";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "load-bmfont-1.3.0" = {
      name = "load-bmfont";
      packageName = "load-bmfont";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-bmfont/-/load-bmfont-1.3.0.tgz";
        sha1 = "bb7e7c710de6bcafcb13cb3b8c81e0c0131ecbc9";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "1x901mk5cdib4xp27v4ivwwr7mhy64r4rk953bzivi5p9lf2bhw88ra2rhkd254xkdx2d3q30zkq239vc4yx4pfsj4hpys8rbr6fif7";
      };
    };
    "mime-db-1.33.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.33.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.33.0.tgz";
        sha512 = "36xnw59ik9fqym00cmwb5nyzg0l03k70cp413f7639j93wgmzk1mh0xjc7i6zz3r6k9xnwh0g5cm5a1f3y8c6plgy4qld7fm887ywh4";
      };
    };
    "mime-types-2.1.18" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.18.tgz";
        sha512 = "22krj1kw7n9z10zdyx7smcaim4bzwqsqzhspwha06q58gcrxfp93hw2cd0vk5crhq5p2dwzqlpacg32lrmp5sjzb798zdzy35mdmkwm";
      };
    };
    "min-document-2.19.0" = {
      name = "min-document";
      packageName = "min-document";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/min-document/-/min-document-2.19.0.tgz";
        sha1 = "7bd282e3f5842ed295bb748cdd9f1ffa2c824685";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "parse-bmfont-ascii-1.0.6" = {
      name = "parse-bmfont-ascii";
      packageName = "parse-bmfont-ascii";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-ascii/-/parse-bmfont-ascii-1.0.6.tgz";
        sha1 = "11ac3c3ff58f7c2020ab22769079108d4dfa0285";
      };
    };
    "parse-bmfont-binary-1.0.6" = {
      name = "parse-bmfont-binary";
      packageName = "parse-bmfont-binary";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-binary/-/parse-bmfont-binary-1.0.6.tgz";
        sha1 = "d038b476d3e9dd9db1e11a0b0e53a22792b69006";
      };
    };
    "parse-bmfont-xml-1.1.3" = {
      name = "parse-bmfont-xml";
      packageName = "parse-bmfont-xml";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-xml/-/parse-bmfont-xml-1.1.3.tgz";
        sha1 = "d6b66a371afd39c5007d9f0eeb262a4f2cce7b7c";
      };
    };
    "parse-headers-2.0.1" = {
      name = "parse-headers";
      packageName = "parse-headers";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-headers/-/parse-headers-2.0.1.tgz";
        sha1 = "6ae83a7aa25a9d9b700acc28698cd1f1ed7e9536";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "pixelmatch-4.0.2" = {
      name = "pixelmatch";
      packageName = "pixelmatch";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixelmatch/-/pixelmatch-4.0.2.tgz";
        sha1 = "8f47dcec5011b477b67db03c243bc1f3085e8854";
      };
    };
    "png-to-ico-1.0.7" = {
      name = "png-to-ico";
      packageName = "png-to-ico";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/png-to-ico/-/png-to-ico-1.0.7.tgz";
        sha512 = "0d17r2fdn94gz4kvvq112pfd3xnqcfdw7zxk2571lbrx35dzfyg95qhkj7wilgm75pz594by5h7v8y060pf11p4i85mi1f56dkf5qc5";
      };
    };
    "pngjs-3.3.3" = {
      name = "pngjs";
      packageName = "pngjs";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pngjs/-/pngjs-3.3.3.tgz";
        sha512 = "3wiswbncddf1vdamqaf5m9cd9040p1dnkvyyal5hy8dyrayya80swr10ngq7g5yinyl80g295yds5gxv5wlamfd28mi0fy8kpidjzfn";
      };
    };
    "process-0.5.2" = {
      name = "process";
      packageName = "process";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.5.2.tgz";
        sha1 = "1638d8a8e34c2f440a91db95ab9aeb677fc185cf";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "0c46ws0x9g3mmkgfmvd78bzvnmv2b8ryg4ah6jvyyqgjv9v994z7xdyvsc4vg9sf98gg7phvy3q1ahgaj5fy3dwzf2rki6bixgl15ip";
      };
    };
    "read-chunk-1.0.1" = {
      name = "read-chunk";
      packageName = "read-chunk";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-chunk/-/read-chunk-1.0.1.tgz";
        sha1 = "5f68cab307e663f19993527d9b589cace4661194";
      };
    };
    "request-2.87.0" = {
      name = "request";
      packageName = "request";
      version = "2.87.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.87.0.tgz";
        sha512 = "0vnsbflzj7gxa33r47bzsiaf7jc00b9iqkqdz8l7n9x5dgdgbq1qpcqqslds1arazipz8pjr4m5rf4ikg4d59d49gn9dky0ds921jkx";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "3xbm0dkya4bc3zwfwpdzbl8ngq0aai5ihlp2v3s39y7162c7wyvv9izj3g8hv6dy6vm2lq48lmfzygk0kxwbjb6xic7k4a329j99p8r";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "2v99f22kh56y72d3s8wrgdvf5n10ry40dh3fwnsxr4d5rfvxdfxfmc3qyqkscnj4f8799jy9bpg6cm21x2d811dr9ib83wjrlmkg6k1";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "1dn291mjsda42w8kldlbmngk6dhjxfbvvd5lckyqmwbjaj6069iq3wx0nvcfglwnpddz2qa93lzf4hv77iz43bd2qixa079sjzl799n";
      };
    };
    "sshpk-1.14.2" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.14.2.tgz";
        sha1 = "c6fc61648a3d9c4e764fd3fcdf4ea105e492ba98";
      };
    };
    "stream-to-0.2.2" = {
      name = "stream-to";
      packageName = "stream-to";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to/-/stream-to-0.2.2.tgz";
        sha1 = "84306098d85fdb990b9fa300b1b3ccf55e8ef01d";
      };
    };
    "stream-to-buffer-0.1.0" = {
      name = "stream-to-buffer";
      packageName = "stream-to-buffer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to-buffer/-/stream-to-buffer-0.1.0.tgz";
        sha1 = "26799d903ab2025c9bd550ac47171b00f8dd80a9";
      };
    };
    "tinycolor2-1.4.1" = {
      name = "tinycolor2";
      packageName = "tinycolor2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinycolor2/-/tinycolor2-1.4.1.tgz";
        sha1 = "f4fad333447bc0b07d4dc8e9209d8f39a8ac77e8";
      };
    };
    "tough-cookie-2.3.4" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.4.tgz";
        sha512 = "0ncm6j3cjq1f26mzjf04k9bkw1b08w53s4qa3a11c1bdj4pgnqv1422c1xs5jyy6y1psppjx52fhagq5zkjkgrcpdkxcdiry96r77jd";
      };
    };
    "trim-0.0.1" = {
      name = "trim";
      packageName = "trim";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim/-/trim-0.0.1.tgz";
        sha1 = "5858547f6b290757ee95cccc666fb50084c460dd";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "untildify-3.0.3" = {
      name = "untildify";
      packageName = "untildify";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/untildify/-/untildify-3.0.3.tgz";
        sha512 = "0l4awya87dx6bnxaywh0dn50ka8hybj603k75d98vlwj9grqfcmaib9hhjy52nsgm62f39v0nnv4yn268jpjy7n9y7wpbwzqwkkyac9";
      };
    };
    "url-regex-3.2.0" = {
      name = "url-regex";
      packageName = "url-regex";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-regex/-/url-regex-3.2.0.tgz";
        sha1 = "dbad1e0c9e29e105dd0b1f09f6862f7fdb482724";
      };
    };
    "uuid-3.2.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz";
        sha512 = "0843vl1c974n8kw5kn0kvhvhwk8y8jydr0xkwwl2963xxmkw4ingk6xj9c8m48jw2i95giglxzq5aw5v5mij9kv7fzln8pxav1cr6cd";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "winreg-1.2.4" = {
      name = "winreg";
      packageName = "winreg";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winreg/-/winreg-1.2.4.tgz";
        sha1 = "ba065629b7a925130e15779108cf540990e98d1b";
      };
    };
    "xhr-2.5.0" = {
      name = "xhr";
      packageName = "xhr";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xhr/-/xhr-2.5.0.tgz";
        sha512 = "36z7hw07wb42na5hy12xmsrg9yzd3hd5ln8y3wyq88qh4xvxr2lp07bbp5la5254mf8qaimgg1plwzvvvsmvj0mcma17p1dbvzlwyg2";
      };
    };
    "xml-parse-from-string-1.0.1" = {
      name = "xml-parse-from-string";
      packageName = "xml-parse-from-string";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml-parse-from-string/-/xml-parse-from-string-1.0.1.tgz";
        sha1 = "a9029e929d3dbcded169f3c6e28238d95a5d5a28";
      };
    };
    "xml2js-0.4.19" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.19.tgz";
        sha512 = "3skianymbfq4rg2v5c1vwsz2kmxfik60qa892wh6a3rydd1wrv3l4vgyr8v4wd8krdf42jbmq7blp0ksbmwm332q5yr922fj8jngiks";
      };
    };
    "xmlbuilder-9.0.7" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "9.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz";
        sha1 = "132ee63d2ec5565c557e20f4c22df9aca686b10d";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
  };
in
{
  "riot-desktop-file:../riot-web/electron_app" = nodeEnv.buildNodePackage {
    name = "riot-web";
    packageName = "riot-web";
    version = "0.15.4";
    src = ../riot-web/electron_app;
    dependencies = [
      sources."@types/node-9.6.22"
      sources."ajv-5.5.2"
      sources."applescript-1.0.0"
      sources."asn1-0.2.3"
      sources."assert-plus-1.0.0"
      sources."asynckit-0.4.0"
      (sources."auto-launch-5.0.5" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."aws-sign2-0.7.0"
      sources."aws4-1.7.0"
      sources."bcrypt-pbkdf-1.0.1"
      sources."bignumber.js-2.4.0"
      sources."bmp-js-0.0.3"
      sources."buffer-equal-0.0.1"
      sources."caseless-0.12.0"
      sources."co-4.6.0"
      sources."combined-stream-1.0.6"
      sources."core-util-is-1.0.2"
      sources."dashdash-1.14.1"
      sources."deep-equal-1.0.1"
      sources."delayed-stream-1.0.0"
      sources."dom-walk-0.1.1"
      sources."ecc-jsbn-0.1.1"
      sources."electron-window-state-4.1.1"
      sources."es6-promise-3.3.1"
      sources."exif-parser-0.1.12"
      sources."extend-3.0.1"
      sources."extsprintf-1.3.0"
      sources."fast-deep-equal-1.1.0"
      sources."fast-json-stable-stringify-2.0.0"
      sources."file-type-3.9.0"
      sources."for-each-0.3.3"
      sources."forever-agent-0.6.1"
      sources."form-data-2.3.2"
      sources."getpass-0.1.7"
      sources."global-4.3.2"
      sources."graceful-fs-4.1.11"
      sources."har-schema-2.0.0"
      sources."har-validator-5.0.3"
      sources."http-signature-1.2.0"
      sources."ip-regex-1.0.3"
      sources."is-callable-1.1.3"
      sources."is-function-1.0.1"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."jimp-0.2.28"
      sources."jpeg-js-0.2.0"
      sources."jsbn-0.1.1"
      sources."json-schema-0.2.3"
      sources."json-schema-traverse-0.3.1"
      sources."json-stringify-safe-5.0.1"
      sources."jsonfile-2.4.0"
      sources."jsprim-1.4.1"
      sources."load-bmfont-1.3.0"
      sources."mime-1.6.0"
      sources."mime-db-1.33.0"
      sources."mime-types-2.1.18"
      sources."min-document-2.19.0"
      sources."minimist-1.2.0"
      sources."mkdirp-0.5.1"
      sources."oauth-sign-0.8.2"
      sources."parse-bmfont-ascii-1.0.6"
      sources."parse-bmfont-binary-1.0.6"
      sources."parse-bmfont-xml-1.1.3"
      sources."parse-headers-2.0.1"
      sources."path-is-absolute-1.0.1"
      sources."performance-now-2.1.0"
      sources."pixelmatch-4.0.2"
      sources."png-to-ico-1.0.7"
      sources."pngjs-3.3.3"
      sources."process-0.5.2"
      sources."punycode-1.4.1"
      sources."qs-6.5.2"
      sources."read-chunk-1.0.1"
      sources."request-2.87.0"
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      sources."sshpk-1.14.2"
      sources."stream-to-0.2.2"
      sources."stream-to-buffer-0.1.0"
      sources."tinycolor2-1.4.1"
      sources."tough-cookie-2.3.4"
      sources."trim-0.0.1"
      sources."tunnel-agent-0.6.0"
      sources."tweetnacl-0.14.5"
      sources."untildify-3.0.3"
      sources."url-regex-3.2.0"
      sources."uuid-3.2.1"
      sources."verror-1.10.0"
      sources."winreg-1.2.4"
      sources."xhr-2.5.0"
      sources."xml-parse-from-string-1.0.1"
      sources."xml2js-0.4.19"
      sources."xmlbuilder-9.0.7"
      sources."xtend-4.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A feature-rich client for Matrix.org";
    };
    production = false;
    bypassCache = true;
  };
}